---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Promotion of : @gitCommit@"
  name: hello-kotlin-service
spec:
  template:
    metadata:
      annotations:
        git_commit_id: "@gitCommit@"
    spec:
      containers:
        - name: hello-kotlin-service
          image: "@docker-registry.url@/hello-kotlin-service:@gitCommit@"
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: hello-kotlin-service
spec:
  hosts:
    - stg-hello-kotlin-service.HOSTNAME.com
